API_KEY = 'QUGW4OGFEOFHHTN2'
ENDPOINT_SCHEMA_URL = 'https://psrc-1wydj.us-east-2.aws.confluent.cloud'
API_SECRET_KEY = 'XCq/RpbyP7Rx8KFJCg15HYnAJKsqjhJxPt7L+VXY4LUm35yDBYLz6VuboJdlI2U0'
BOOTSTRAP_SERVER = 'pkc-ymrq7.us-east-2.aws.confluent.cloud:9092'
SECURITY_PROTOCOL = 'SASL_SSL'
SSL_MECHANISM = 'PLAIN'
SCHEMA_REGISTRY_API_KEY = 'QBTBODTOH5L3J7UK'
SCHEMA_REGISTRY_API_SECRET = 'zHgYVThLOM7X46nbG2oXTOV9qe7n7j/8kOvlRnuM+aap1QojxH5qmMxJ/cLeI0XY'
xd
def config_values():
    return API_KEY, ENDPOINT_SCHEMA_URL, API_SECRET_KEY, BOOTSTRAP_SERVER, SECURITY_PROTOCOL, SSL_MECHANISM, SCHEMA_REGISTRY_API_KEY, SCHEMA_REGISTRY_API_SECRET
